services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    expose:
      - "80"
      - "8443"
    networks:
      - telemt-network
    restart: unless-stopped

  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    expose:
      - "8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - telemt-network
    restart: unless-stopped
    depends_on:
      - nginx
      - telemt

  telemt:
    image: whn0thacked/telemt-docker:3.3.28
    container_name: telemt
    restart: unless-stopped
    environment:
      RUST_LOG: "info"
    volumes:
      - ./telemt.toml:/etc/telemt.toml:ro
    security_opt:
      - no-new-privileges:true
    expose:
      - "443"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=16m
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    networks:
      - telemt-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  telemt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16