events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 8443 ssl;
        server_name _;
        ssl_certificate /etc/nginx/ssl/live/beatvault.ru/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/live/beatvault.ru/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}